version: "3"
services:
    nginx:
        restart: always
        image: nginx:1.13
        volumes:
            - ./nginx/autoclassweb_nginx.conf:/etc/nginx/conf.d/default.conf
            - flaskapp-static:/www/static
            - ./logs:/var/log/nginx
        ports:
            - 8000:80
        depends_on:
            - flaskapp


    flaskapp:
        restart: always
        image: pierrepo/autoclassweb:latest
        volumes:
            - flaskapp-static:/app/flaskapp/static
            - ./results:/app/results
            - ./logs:/app/logs
            - ./config:/app/config
        environment:
            FLASK_DEBUG: 1
        command: "gunicorn --config gunicorn.conf flaskapp:app"

volumes:
    flaskapp-static:
